### ISSUE TITLE
original form of FCPROCESS_MSC.m (for non-tasked fMRI)

### ISSUE THREAD

**Issue by kelmok** [MidnightScanClub/MSC_Gratton2018_Codebase#1]
Hi,
I'd like to know if the original FCPROCESS_MSC.m code associated with Gordon et al., 2017 is available somewhere? I could not locate in the original MSC repo
Thanks

**Comment by evangordon** [comment]
This script has now been added, in the original MSC repo and here. Thanks for alerting us it was missing.

**Comment by laumannt** [comment]
Just to be sure, it should be FCPROCESS_MSC.m not FCPROCESS_HCP.m
Tim

**Comment by vanandrew** [comment]
Whoops :/ These filenames are too similar... It's fixed now.

Andrew Van
Biomedical Engineering, Graduate Student
Washington University in St. Louis
vanandrew@wustl.edu

On Tue, Jun 25, 2019 at 9:37 PM, laumannt <notifications@github.com> wrote:
Just to be sure, it should be FCPROCESS_MSC.m not FCPROCESS_HCP.m
Tim
